version: '3.7'
services:
  web:
    build:
      context: .
    command: sh -c "rm -f tmp/pids/server.pid && bundle install --jobs 10 --retry 5 && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      RAILS_ENV: development
    ports:
      - 3000:3000
    networks:
      - app-network

volumes:
  bundle_vendor:

networks:
  app-network:
    driver: bridge